apiVersion: apps/v1
kind: Deployment
metadata: 
  name: books-svc
  labels:
    app: books-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-svc
  template:
    metadata:
      labels: 
        app: books-svc 
    spec:
      containers:
      - name: books-svc
        image: shaikkhajaibrahim/libbookssvc:1.0
        resources: 
          requests: 
            cpu: 30m
            memory: 120M
          limits:
            cpu: 100m
            memory: 300M
        env:
        - name: DATABASE_URL 
          value: "postgresql://user:password@books-db:5432/booksdb"
        - name:  SECRET_KEY
          value: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service  
metadata:
  name: books-svc
spec: 
  selector:
    app: books-svc
  type:  "ClusterIP"
  ports:
  - port: 8080
    targetPort: 8080
                 
           