apiVersion: apps/v1
kind: Deployment
metadata: 
  name: user-db
  labels: 
    app: user-db
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: user-db
  template:
    metadata:
      name: user-db
      labels: 
        app: user-db
    spec:
      containers:
      - name: user-db
        image: postgres:15-alpine
        resources: 
          requests: 
            cpu: 30m
            memory: 120M
          limits:
            cpu: 90m
            memory: 300M
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        - name:  POSTGRES_DB
          value: userdb
        ports:
        - name: user-db
          containerPort: 8080


---
apiVersion: v1
kind: Service
metadata: 
  name: user-db
  labels:
   app: user-db
spec: 
  selector:
    app: user-db
  type: "ClusterIP"
  ports:
  - name: user-db
    port: 8080